### ISSUE TITLE
basic-auth versioning

### ISSUE THREAD

**Issue by nickmarx12345678** [Springest/opsworks-logstash#2]
Hi,
Apologies since I'm still getting up to speed with Chef, but how did you deal with getting the correct version of the elasticsearch http auth plugin so that you can use Kibana and ElasticSearch 1.x.x? The issue I'm running into (I believe) is that by bumping to Elasticsearch 1.0.1, I'm breaking the auth plugin
Thanks!

**Comment by lizhubertz** [comment]
Hey @nickmarx12345678 - sorry for the insanely late reply, but you're right, we're no longer maintaining this repository. Thanks for your interest!
