### ISSUE TITLE
Problems in speed-up a new instance for ElasticSearch cluster

### ISSUE THREAD

**Issue by micheleorsi** [Springest/opsworks-logstash#5]
I followed the whole procedure and once I try to start the instance for ElasticSearch layer I got the follwoing error ..

I tried starting up an Ubuntu machine (14.04 LTS) or an Amazon machine. Same error

> [2014-08-03T15:48:11+00:00] INFO: Forking chef instance to converge...
> [2014-08-03T15:48:12+00:00] INFO: *** Chef 11.10.4 ***
> [2014-08-03T15:48:12+00:00] INFO: Chef-client pid: 6380
> [2014-08-03T15:48:13+00:00] INFO: Setting the run_list to ["opsworks_custom_cookbooks::load", "opsworks_custom_cookbooks::execute"] from JSON
> [2014-08-03T15:48:13+00:00] WARN: Run List override has been provided.
> [2014-08-03T15:48:13+00:00] WARN: Original Run List: [recipe[opsworks_custom_cookbooks::load], recipe[opsworks_custom_cookbooks::execute]]
> [2014-08-03T15:48:13+00:00] WARN: Overridden Run List: [recipe[opsworks_initial_setup], recipe[ssh_host_keys], recipe[ssh_users], recipe[mysql::client], recipe[dependencies], recipe[ebs], recipe[opsworks_ganglia::client], recipe[opsworks_stack_state_sync], recipe[elasticsearch::install], recipe[elasticsearch::packages], recipe[deploy::default], recipe[test_suite], recipe[opsworks_cleanup]]
> [2014-08-03T15:48:13+00:00] INFO: Run List is [recipe[opsworks_initial_setup], recipe[ssh_host_keys], recipe[ssh_users], recipe[mysql::client], recipe[dependencies], recipe[ebs], recipe[opsworks_ganglia::client], recipe[opsworks_stack_state_sync], recipe[elasticsearch::install], recipe[elasticsearch::packages], recipe[deploy::default], recipe[test_suite], recipe[opsworks_cleanup]]
[2014-08-03T15:48:13+00:00] INFO: Run List expands to [opsworks_initial_setup, ssh_host_keys, ssh_users, mysql::client, dependencies, ebs, opsworks_ganglia::client, opsworks_stack_state_sync, elasticsearch::install, elasticsearch::packages, deploy::default, test_suite, opsworks_cleanup]
> [2014-08-03T15:48:13+00:00] INFO: Starting Chef Run for elastic-search2.localdomain
> [2014-08-03T15:48:13+00:00] INFO: Running start handlers
> [2014-08-03T15:48:13+00:00] INFO: Start handlers complete.
> [2014-08-03T15:48:13+00:00] INFO: HTTP Request Returned 404 Not Found: Object not found: /reports/nodes/elastic-search2.localdomain/runs
> [2014-08-03T15:48:44+00:00] INFO: HTTP Request Returned 412 Precondition Failed: Could not satisfy version constraints for: yum
> 
> ================================================================================
> Error Resolving Cookbooks for Run List:
> ================================================================================
>  
> Missing Cookbooks:
> ------------------
> Could not satisfy version constraints for: yum
> 
> 
> Expanded Run List:
> ------------------
> * opsworks_initial_setup
> * ssh_host_keys
> * ssh_users
> * mysql::client
> * dependencies
> * ebs
> * opsworks_ganglia::client
> * opsworks_stack_state_sync
> * elasticsearch::install
> * elasticsearch::packages
> * deploy::default
> * test_suite
> * opsworks_cleanup
> 
> 
> [2014-08-03T15:48:44+00:00] ERROR: Running exception handlers
> [2014-08-03T15:48:44+00:00] ERROR: Exception handlers complete
> [2014-08-03T15:48:44+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache/chef-stacktrace.out
> [2014-08-03T15:48:44+00:00] ERROR: 412 "Precondition Failed"
> [2014-08-03T15:48:44+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
> 

And here is the Stacktrace:

> 
> Generated at 2014-08-03 15:46:22 +0000
> Net::HTTPServerException: 412 "Precondition Failed"
> /opt/aws/opsworks/local/lib/ruby/2.0.0/net/http/response.rb:119:in `error!'
> /opt/aws/opsworks/releases/20140620104520_315/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/http.rb:140:in `request'
> /opt/aws/opsworks/releases/20140620104520_315/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/http.rb:121:in `post'
> /opt/aws/opsworks/releases/20140620104520_315/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/policy_builder/expand_node_object.rb:170:in `sync_cookbooks'
> /opt/aws/opsworks/releases/20140620104520_315/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/policy_builder/expand_node_object.rb:68:in `setup_run_context'
> /opt/aws/opsworks/releases/20140620104520_315/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/client.rb:252:in `setup_run_context'
> /opt/aws/opsworks/releases/20140620104520_315/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/client.rb:413:in `do_run'
> /opt/aws/opsworks/releases/20140620104520_315/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/client.rb:200:in `block in run'
> /opt/aws/opsworks/releases/20140620104520_315/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/client.rb:194:in `fork'
> /opt/aws/opsworks/releases/20140620104520_315/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/client.rb:194:in `run'
> /opt/aws/opsworks/releases/20140620104520_315/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/application.rb:215:in `run_chef_client'
> /opt/aws/opsworks/releases/20140620104520_315/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/application/client.rb:314:in `block in run_application'
> /opt/aws/opsworks/releases/20140620104520_315/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/application/client.rb:306:in `loop'
> /opt/aws/opsworks/releases/20140620104520_315/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/application/client.rb:306:in `run_application'
> /opt/aws/opsworks/releases/20140620104520_315/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/application.rb:66:in `run'
> /opt/aws/opsworks/releases/20140620104520_315/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/bin/chef-client:26:in `<top (required)>'
> /opt/aws/opsworks/current/bin/chef-client:16:in `load'
> /opt/aws/opsworks/current/bin/chef-client:16:in `<main>'

**Comment by lizhubertz** [comment]
Hey @guillaumepotier @chrishenderson & @micheleorsi - long time coming, but you're right, we're no longer maintaining this repository. But thanks for your interest! Definitely check out some of the maintained forks, or email us at developers@springest.com if you're interested in taking it over.
