### ISSUE TITLE
Could not satisfy version constraints for: yum

### ISSUE THREAD

**Issue by gentitope** [Springest/opsworks-logstash#8]
This is the error i came across when booting:
# Could not satisfy version constraints for: yum

How can i slove this issue?

Thanks

**Comment by toddlers** [comment]
@chrishenderson looks like all the cookbooks present in the repo are not required . I see ant/database/nagios and windows. Correct me if I am wrong.

**Comment by lizhubertz** [comment]
@chrishenderson @toddlers @gentitope Apologies for the long silence! Unfortunately we're no longer using and maintaining this project. I see a couple of active forks - maybe you can try your luck with one of those. Thanks for your interest in the project!
